create table USUARIO
(
	IDUSUARIO INTEGER not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
	NOME VARCHAR(255)
);
create table USUARIOTAREFA
(
	IDTAREFA INTEGER not null,
	IDUSUARIO INTEGER not null,
	primary key (IDTAREFA, IDUSUARIO)
);
create table PROJETO
(
	IDPROJETO INTEGER not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
	DESCRICAO VARCHAR(255)
);
create table TAREFA
(
	IDTAREFA INTEGER not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
	IDPROJETO INTEGER,
	DESCRICAO VARCHAR(255),
	STATUS BOOLEAN,
	DATAINICIO DATE,
	DATAFINAL DATE,
	DIASCONCLUSAO INTEGER,
        PERCENTUAL INTEGER
);
create table TAREFAASSOCIADA
(
	IDTAREFA INTEGER not null,
	IDTAREFAASSOCIADA INTEGER not null,
        STATUS BOOLEAN not null,
	primary key (IDTAREFA, IDTAREFAASSOCIADA)
);