/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dcc171.pkg2017.pkg3.tbr3;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.Projeto;
import models.Tarefa;
import models.TarefaListModel;
import models.TarefaTableModel;
import models.Usuario;
import models.UsuarioListModel;
import percistence.TarefaDAO;
import percistence.UsuarioDAO;

/**
 *
 * @author fhnri
 */
public class janelaTarefa extends javax.swing.JFrame {
    public Projeto projeto=null;
    public Tarefa tarefa=null;
    public JanelaProjetos janelaProj=null;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form JanelaTarefas
     */
    public janelaTarefa(JanelaProjetos j,Projeto p,Tarefa t) {
        
        janelaProj=j;
        
        initComponents();
        
        projeto=p;
        
        if(t!=null){
        
            tarefa=t;
            descricao.setText(t.getDescricao());
            if(t.getInicio()!=null){
                dataInicio.setText(sdf.format(t.getInicio()));
            }
            if(t.getFim()!=null){
                dataFinal.setText(sdf.format(t.getFim()));
            }
            percentual.setText(Integer.toString(t.getPercentual()));
            diasConclusao.setText(Integer.toString(t.getDiasConclusao()));
            feito.setSelected(t.isFinished());
            populaTarefasAssociada();
            populaUsuariosTarefas();
        }else{
        
            tarefa=new Tarefa(p);
        
        }
        
        exibeUsuarios();
        
    }
    
    public void populaTarefasAssociada(){
        ArrayList<Tarefa> tarefas=TarefaDAO.getInstance().getTarefasAssocidas(this.tarefa);
        lstTarefasAssociadas.setModel(new TarefaListModel(tarefas));
    }
    
    public void populaUsuariosTarefas(){
        ArrayList<Usuario> usuarios=TarefaDAO.getInstance().getUsuariosTarefas(this.tarefa);
        lstUsuariosTarefa.setModel(new UsuarioListModel(usuarios));
    }
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dataInicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dataFinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        diasConclusao = new javax.swing.JTextField();
        feito = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnSalvaTarefa = new javax.swing.JButton();
        btnCancelaTarefa = new javax.swing.JButton();
        percentual = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTarefasAssociadas = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        btnAddTarefaAssociada = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxUsuarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuariosTarefa = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        removeTarefaAssociada = new javax.swing.JButton();
        removeUsuario = new javax.swing.JButton();

        jLabel3.setText("Data do início");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Descrição da tarefa");

        jLabel2.setText("Data do início");

        jLabel4.setText("Data final");

        jLabel5.setText("Dias para a conclusão");

        feito.setText("Feito");
        feito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feitoActionPerformed(evt);
            }
        });

        jLabel6.setText("Percentual de conclusão");

        btnSalvaTarefa.setText("Salvar");
        btnSalvaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaTarefaActionPerformed(evt);
            }
        });

        btnCancelaTarefa.setText("Cancelar");
        btnCancelaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaTarefaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstTarefasAssociadas);

        jLabel8.setText("Tarefas associadas");

        btnAddTarefaAssociada.setText("Adicionar tarefa");
        btnAddTarefaAssociada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTarefaAssociadaActionPerformed(evt);
            }
        });

        jLabel7.setText("Usuarios");

        jComboBoxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsuariosActionPerformed(evt);
            }
        });

        lstUsuariosTarefa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstUsuariosTarefa);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        removeTarefaAssociada.setText("Remove tarefa associada");
        removeTarefaAssociada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTarefaAssociadaActionPerformed(evt);
            }
        });

        removeUsuario.setText("Remove usuario");
        removeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeUsuario))
                    .addComponent(descricao)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(diasConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addComponent(percentual)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAddTarefaAssociada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelaTarefa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvaTarefa))
                            .addComponent(removeTarefaAssociada, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(20, 20, 20)
                                .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diasConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUsuarios)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(129, 129, 129)
                        .addComponent(removeTarefaAssociada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelaTarefa)
                            .addComponent(btnSalvaTarefa)
                            .addComponent(btnAddTarefaAssociada)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaTarefaActionPerformed
        if(descricao.getText().length()>0){
            tarefa.setDescricao(descricao.getText());
            if(diasConclusao.getText().length()>0){
            
                tarefa.setDiasConclusao(Integer.parseInt(diasConclusao.getText()));
            
            }else{
                tarefa.setDiasConclusao(0);
            }
            
            try {
                
                if(dataInicio.getText().length()>0){
                    tarefa.setInicio(sdf.parse(dataInicio.getText()));
                }else{
                    tarefa.setInicio(null);
                }
                if(dataFinal.getText().length()>0){
                    tarefa.setFim(sdf.parse(dataFinal.getText()));
                }else{
                    tarefa.setFim(null);
                }
            } catch (ParseException ex) {
                Logger.getLogger(janelaTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(percentual.getText().length()>0){
                tarefa.setPercentual(Integer.parseInt(percentual.getText()));
            }else{
                tarefa.setPercentual(0);
            }
            
            tarefa.setStatus(feito.isSelected());
            
            TarefaDAO.getInstance().Save(tarefa);
            janelaProj.populaTarefas();
            setVisible(false);
            dispose();
        }else{
            JOptionPane.showMessageDialog(new JFrame(), "A descrição da tarefa não pode ficar em branco.", "Erro",JOptionPane.ERROR_MESSAGE);            
        }
        janelaProj.listaProjetos.updateUI();
    }//GEN-LAST:event_btnSalvaTarefaActionPerformed

    public void exibeUsuarios(){
        
        
        Vector usuarios = new Vector();
        ArrayList<Usuario> u = UsuarioDAO.getInstance().getUsuarios();
        for(Usuario aux:u){
            usuarios.addElement(aux);
        }
        jComboBoxUsuarios.setModel(new DefaultComboBoxModel<Usuario>(usuarios)); 
    }
    
    public void uncheckFeito(){
        if(tarefa.isFinished()){
            tarefa.setStatus(false);
            TarefaDAO.getInstance().Save(tarefa);
            feito.setSelected(false);
            janelaProj.populaTarefas();
            JOptionPane.showMessageDialog(new JFrame(), "A tarefa foi desmarcada como feita, pois há tarefas pendentes.", "Erro",JOptionPane.ERROR_MESSAGE);            
        }
    }
    
    
    private void btnCancelaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaTarefaActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelaTarefaActionPerformed

    private void btnAddTarefaAssociadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTarefaAssociadaActionPerformed
        JanelaTarefas janela = new JanelaTarefas(tarefa,this);
        janela.setLocationRelativeTo(null);
        janela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janela.setVisible(true);
    }//GEN-LAST:event_btnAddTarefaAssociadaActionPerformed

    private void jComboBoxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsuariosActionPerformed
       
        
        
    }//GEN-LAST:event_jComboBoxUsuariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TarefaDAO.getInstance().adicionaUsuarioTarefa(tarefa, (Usuario) jComboBoxUsuarios.getSelectedItem());
        populaUsuariosTarefas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void feitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feitoActionPerformed
        if(!TarefaDAO.getInstance().podeConcluir(tarefa)){
            feito.setSelected(false);
            JOptionPane.showMessageDialog(new JFrame(), "Está tarefa não pode ser concluída, pois há tarefas relacionadas pendentes.", "Erro",JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_feitoActionPerformed

    private void removeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUsuarioActionPerformed
        Usuario usuario = lstUsuariosTarefa.getSelectedValue();
        if(usuario!=null){
            TarefaDAO.getInstance().deletaUsuarioTarefa(tarefa, usuario);
            populaUsuariosTarefas();
        }
    }//GEN-LAST:event_removeUsuarioActionPerformed

    private void removeTarefaAssociadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTarefaAssociadaActionPerformed
       Tarefa tarefaAssociada = lstTarefasAssociadas.getSelectedValue();
       if(tarefaAssociada!=null){
            TarefaDAO.getInstance().deletaTarefaAssociada(tarefa, tarefaAssociada);
            populaTarefasAssociada();
       }
    }//GEN-LAST:event_removeTarefaAssociadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTarefaAssociada;
    private javax.swing.JButton btnCancelaTarefa;
    private javax.swing.JButton btnSalvaTarefa;
    private javax.swing.JTextField dataFinal;
    private javax.swing.JTextField dataInicio;
    private javax.swing.JTextField descricao;
    private javax.swing.JTextField diasConclusao;
    private javax.swing.JCheckBox feito;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Usuario> jComboBoxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList<Tarefa> lstTarefasAssociadas;
    private javax.swing.JList<Usuario> lstUsuariosTarefa;
    private javax.swing.JTextField percentual;
    private javax.swing.JButton removeTarefaAssociada;
    private javax.swing.JButton removeUsuario;
    // End of variables declaration//GEN-END:variables
}
